features=[]
target=""

[train_test_split]
test_size=0.2
random_state=1

[linear_regression]
fit_intercept=true

[logistic_regression]
penalty="l2"
fit_intercept=true
random_state=1

[random_forest]
n_estimators=100
max_depth=10
n_jobs=-1
random_state=1
bootstrap=false
class_weight="balanced"